url: https://jerikcruz.github.io # change to your site's url 
baseurl:   # change to your repository 
title: Jerik Cruz # Change to your site's title
description: Researching the causes and consequences of the global rise of knowledge capitalism # leave blank if you don't want to display a description

last_updated: # leave blank if you don't want to display last updated


# Change to your name and contact information
author:
  name: Jerik Cruz
  positition: PhD Candidate
  affiliation: Massachusetts Institute of Technology
  address: Cambridge, MA / Quezon City, PHL
  city-state-zip: '02142 USA / 1108 Philippines'
  email: jpdcruz@mit.edu 
  github: jerikdcruz
  linkedin: www.linkedin.com/in/jerikdcruz

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings

# deployment
host: localhost
port: 4000

# remote_theme: EricMFink/Akademicky #uncomment to use EricMFink/Akademicky as remote theme

gems:
  - jekyll-pandoc

markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:categories/:year/:month/:day/:title/
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator
include: ['_pages']
exclude: ['Gemfile']
keep_files: []
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: code
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/EricMFink.github.com/ #change to your GitHub account

jquery_version: "1.12.4"
anchorjs_version: "3.2.2"

plugins:
  - jekyll-spaceship

# Where things are
jekyll-spaceship:
  # default enabled processors
  processors:
    - table-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
